package com.chat.zipchat.clone.Model;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatListPojoDaoConfig;
    private final DaoConfig contactResponseDaoConfig;
    private final DaoConfig localDataPojoDaoConfig;
    private final DaoConfig groupsDaoConfig;
    private final DaoConfig groupItemsDaoConfig;
    private final DaoConfig favouritePojoDaoConfig;
    private final DaoConfig acceptRejectPojoDaoConfig;
    private final DaoConfig groupMemberDaoConfig;
    private final DaoConfig resultItemDaoConfig;
    private final DaoConfig chatPojoDaoConfig;

    private final ChatListPojoDao chatListPojoDao;
    private final ContactResponseDao contactResponseDao;
    private final LocalDataPojoDao localDataPojoDao;
    private final GroupsDao groupsDao;
    private final GroupItemsDao groupItemsDao;
    private final FavouritePojoDao favouritePojoDao;
    private final AcceptRejectPojoDao acceptRejectPojoDao;
    private final GroupMemberDao groupMemberDao;
    private final ResultItemDao resultItemDao;
    private final ChatPojoDao chatPojoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatListPojoDaoConfig = daoConfigMap.get(ChatListPojoDao.class).clone();
        chatListPojoDaoConfig.initIdentityScope(type);

        contactResponseDaoConfig = daoConfigMap.get(ContactResponseDao.class).clone();
        contactResponseDaoConfig.initIdentityScope(type);

        localDataPojoDaoConfig = daoConfigMap.get(LocalDataPojoDao.class).clone();
        localDataPojoDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        groupItemsDaoConfig = daoConfigMap.get(GroupItemsDao.class).clone();
        groupItemsDaoConfig.initIdentityScope(type);

        favouritePojoDaoConfig = daoConfigMap.get(FavouritePojoDao.class).clone();
        favouritePojoDaoConfig.initIdentityScope(type);

        acceptRejectPojoDaoConfig = daoConfigMap.get(AcceptRejectPojoDao.class).clone();
        acceptRejectPojoDaoConfig.initIdentityScope(type);

        groupMemberDaoConfig = daoConfigMap.get(GroupMemberDao.class).clone();
        groupMemberDaoConfig.initIdentityScope(type);

        resultItemDaoConfig = daoConfigMap.get(ResultItemDao.class).clone();
        resultItemDaoConfig.initIdentityScope(type);

        chatPojoDaoConfig = daoConfigMap.get(ChatPojoDao.class).clone();
        chatPojoDaoConfig.initIdentityScope(type);

        chatListPojoDao = new ChatListPojoDao(chatListPojoDaoConfig, this);
        contactResponseDao = new ContactResponseDao(contactResponseDaoConfig, this);
        localDataPojoDao = new LocalDataPojoDao(localDataPojoDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);
        groupItemsDao = new GroupItemsDao(groupItemsDaoConfig, this);
        favouritePojoDao = new FavouritePojoDao(favouritePojoDaoConfig, this);
        acceptRejectPojoDao = new AcceptRejectPojoDao(acceptRejectPojoDaoConfig, this);
        groupMemberDao = new GroupMemberDao(groupMemberDaoConfig, this);
        resultItemDao = new ResultItemDao(resultItemDaoConfig, this);
        chatPojoDao = new ChatPojoDao(chatPojoDaoConfig, this);

        registerDao(ChatListPojo.class, chatListPojoDao);
        registerDao(ContactResponse.class, contactResponseDao);
        registerDao(LocalDataPojo.class, localDataPojoDao);
        registerDao(Groups.class, groupsDao);
        registerDao(GroupItems.class, groupItemsDao);
        registerDao(FavouritePojo.class, favouritePojoDao);
        registerDao(AcceptRejectPojo.class, acceptRejectPojoDao);
        registerDao(GroupMember.class, groupMemberDao);
        registerDao(ResultItem.class, resultItemDao);
        registerDao(ChatPojo.class, chatPojoDao);
    }

    public void clear() {
        chatListPojoDaoConfig.clearIdentityScope();
        contactResponseDaoConfig.clearIdentityScope();
        localDataPojoDaoConfig.clearIdentityScope();
        groupsDaoConfig.clearIdentityScope();
        groupItemsDaoConfig.clearIdentityScope();
        favouritePojoDaoConfig.clearIdentityScope();
        acceptRejectPojoDaoConfig.clearIdentityScope();
        groupMemberDaoConfig.clearIdentityScope();
        resultItemDaoConfig.clearIdentityScope();
        chatPojoDaoConfig.clearIdentityScope();
    }

    public ChatListPojoDao getChatListPojoDao() {
        return chatListPojoDao;
    }

    public ContactResponseDao getContactResponseDao() {
        return contactResponseDao;
    }

    public LocalDataPojoDao getLocalDataPojoDao() {
        return localDataPojoDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

    public GroupItemsDao getGroupItemsDao() {
        return groupItemsDao;
    }

    public FavouritePojoDao getFavouritePojoDao() {
        return favouritePojoDao;
    }

    public AcceptRejectPojoDao getAcceptRejectPojoDao() {
        return acceptRejectPojoDao;
    }

    public GroupMemberDao getGroupMemberDao() {
        return groupMemberDao;
    }

    public ResultItemDao getResultItemDao() {
        return resultItemDao;
    }

    public ChatPojoDao getChatPojoDao() {
        return chatPojoDao;
    }

}
