package com.chat.zipchat.clone.Model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVOURITE_POJO".
*/
public class FavouritePojoDao extends AbstractDao<FavouritePojo, Long> {

    public static final String TABLENAME = "FAVOURITE_POJO";

    /**
     * Properties of entity FavouritePojo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FavouriteId = new Property(1, String.class, "FavouriteId", false, "FAVOURITE_ID");
    }


    public FavouritePojoDao(DaoConfig config) {
        super(config);
    }
    
    public FavouritePojoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVOURITE_POJO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FAVOURITE_ID\" TEXT);"); // 1: FavouriteId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FAVOURITE_POJO_FAVOURITE_ID ON \"FAVOURITE_POJO\"" +
                " (\"FAVOURITE_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVOURITE_POJO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FavouritePojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String FavouriteId = entity.getFavouriteId();
        if (FavouriteId != null) {
            stmt.bindString(2, FavouriteId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FavouritePojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String FavouriteId = entity.getFavouriteId();
        if (FavouriteId != null) {
            stmt.bindString(2, FavouriteId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FavouritePojo readEntity(Cursor cursor, int offset) {
        FavouritePojo entity = new FavouritePojo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // FavouriteId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FavouritePojo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFavouriteId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FavouritePojo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FavouritePojo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FavouritePojo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
